In [1]:
try: 
    import seaborn as sns
except:
    %pip install seaborn
    import seaborn as sns
try:
    import pymc as pm # For MCMC
except:
    %pip install pymc
    import pymc as pm
try:
    import arviz as az # For MCMC package
except:
    %pip install arviz
    import arviz as az
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
try:
    import corner
except:
    %pip install corner
    import corner

import iz

print(pm.__version__)

WARNING (pytensor.configdefaults): g++ not detected!  PyTensor will be unable to compile C-implementations and will default to Python. Performance may be severely degraded. To remove this warning, set PyTensor flags cxx to an empty string.
WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.


5.15.1


In [22]:
df1 = iz.dfg(1,4).astype('int64')
iz.negative_binomial_gof(df1["MT-CO3"])

Estimated parameters: r = 4.551250214259007, p = 0.14797146223604726
Observed frequencies:
 [  1   4   7  11  11  12  26  35  32  36  39  54  74  79  68  88  92 107
 101  82  98  84 120  78 111  89  91 103 101  82  76  70  60  63  60  48
  50  45  42  56  44  30  37  24  37  23  19  20  18  14  13  15  11  10
   6   8   4   8   7   8   5   4   2   2   2   3   4   1   1   1   2   3
   4   1   1   1   1   1   1   1   1   1   1   1   1]
Expected frequencies:
 [4.85034310e-01 1.88086365e+00 4.44807665e+00 8.27616872e+00
 1.33119705e+01 1.93979617e+01 2.63099008e+01 3.37893031e+01
 4.15692683e+01 4.93936363e+01 5.70301488e+01 6.42785794e+01
 7.09748485e+01 7.69920826e+01 8.22394563e+01 8.66595233e+01
 9.02246047e+01 9.29326785e+01 9.48031047e+01 9.58724275e+01
 9.61904233e+01 9.58164983e+01 9.48164979e+01 9.32599527e+01
 9.12177596e+01 8.87602801e+01 8.59558257e+01 8.28694928e+01
 7.95623062e+01 7.60906300e+01 7.25058043e+01 6.88539704e+01
 6.51760489e+01 6.15078387e+01 5.78802092e+01 5.431

(317618979.3727475, 0.0, 4.551250214259007, 0.14797146223604726)

In [23]:
iz.negative_binomial_gof(iz.norm2(df1)["MT-CO3"])

/Users/liuruoque/Desktop/M2R/M2R_Group_12/iz/iz.py:36: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '51.948051948051955' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df1.iloc[i] = df1.iloc[i] / listfinal[i] * s_n
/Users/liuruoque/Desktop/M2R/M2R_Group_12/iz/iz.py:36: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '12.987012987012989' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df1.iloc[i] = df1.iloc[i] / listfinal[i] * s_n
/Users/liuruoque/Desktop/M2R/M2R_Group_12/iz/iz.py:36: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '99.56709956709956' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df1.iloc[i] = df1.iloc[i] / 

Estimated parameters: r = 19.352504477245475, p = 0.1057003571656948
Observed frequencies:
 [1 1 1 ... 1 1 1]
Expected frequencies:
 [1.00000000e-10 1.00000000e-10 1.00000000e-10 ... 1.00000000e-10
 1.00000000e-10 1.42296447e-01]
Chi-Square Statistic: 112819999997139.78
p-value: 0.0
Reject the null hypothesis: The data does not follow a negative binomial distribution.


(112819999997139.78, 0.0, 19.352504477245475, 0.1057003571656948)

In [24]:
file_path = 'datasets/Donor1_CD4_Genes.csv'
df2 = pd.read_csv(file_path)

file_path_meta = 'datasets/mt_genes_metadata.csv'
dfmeta = pd.read_csv(file_path_meta)

protein_coding_genes = dfmeta[dfmeta['gene_type'] == 'protein_coding']
protein_names = protein_coding_genes['gene_name'].tolist()
tRNA_coding_genes = dfmeta[dfmeta['gene_type']=='Mt_tRNA']
tRNA_names = tRNA_coding_genes['gene_name'].tolist()
rRNA_coding_genes = dfmeta[dfmeta['gene_type']=='Mt_rRNA']
rRNA_names = rRNA_coding_genes['gene_name'].tolist()

umi = df2["non-MT"]

iz.negative_binomial_gof(iz.norm1(df1, umi)["MT-ND1"])

250070.22420512204
Estimated parameters: r = 1.145982649715101, p = 0.0003417475442269378
Observed frequencies:
 [53  1  1 ...  1  1  1]
Expected frequencies:
 [2.887e+03 1.000e-10 1.000e-10 ... 1.000e-10 1.000e-10 1.000e-10]
Chi-Square Statistic: 28399999997113.973
p-value: 0.0
Reject the null hypothesis: The data does not follow a negative binomial distribution.


(28399999997113.973, 0.0, 1.145982649715101, 0.0003417475442269378)