In [1]:
try: 
    import seaborn as sns
except:
    %pip install seaborn
    import seaborn as sns
try:
    import pymc as pm # For MCMC
except:
    %pip install pymc
    import pymc as pm
try:
    import arviz as az # For MCMC package
except:
    %pip install arviz
    import arviz as az
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
try:
    import corner
except:
    %pip install corner
    import corner

%pip install iz
import iz

print(pm.__version__)

WARNING (pytensor.configdefaults): g++ not detected!  PyTensor will be unable to compile C-implementations and will default to Python. Performance may be severely degraded. To remove this warning, set PyTensor flags cxx to an empty string.
WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.


Note: you may need to restart the kernel to use updated packages.
5.15.1


In [2]:
df1 = iz.dfg(1,4).astype('int64')
iz.negative_binomial_gof(df1["MT-CO3"])

Estimated parameters: r = 4.551250214259007, p = 0.14797146223604726
Observed frequencies:
 [  1   4   7  11  11  12  26  35  32  36  39  54  74  79  68  88  92 107
 101  82  98  84 120  78 111  89  91 103 101  82  76  70  60  63  60  48
  50  45  42  56  44  30  37  24  37  23  19  20  18  14  13  15  11  10
   6   8   4   8   7   8   5   4   2   2   2   3   4   1   1   1   2   3
   4   1   1   1   1   1   1   1   1   1   1   1   1]
Expected frequencies:
 [4.85034310e-01 1.88086365e+00 4.44807665e+00 8.27616872e+00
 1.33119705e+01 1.93979617e+01 2.63099008e+01 3.37893031e+01
 4.15692683e+01 4.93936363e+01 5.70301488e+01 6.42785794e+01
 7.09748485e+01 7.69920826e+01 8.22394563e+01 8.66595233e+01
 9.02246047e+01 9.29326785e+01 9.48031047e+01 9.58724275e+01
 9.61904233e+01 9.58164983e+01 9.48164979e+01 9.32599527e+01
 9.12177596e+01 8.87602801e+01 8.59558257e+01 8.28694928e+01
 7.95623062e+01 7.60906300e+01 7.25058043e+01 6.88539704e+01
 6.51760489e+01 6.15078387e+01 5.78802092e+01 5.431

(317618979.3727475, 0.0, 4.551250214259007, 0.14797146223604726)

In [3]:
iz.negative_binomial_gof(iz.norm2(df1)["MT-CO3"])

Estimated parameters: r = 19.352504477245475, p = 0.1057003571656948
Observed frequencies:
 [1 1 1 ... 1 1 1]
Expected frequencies:
 [1.00000000e-10 1.00000000e-10 1.00000000e-10 ... 1.00000000e-10
 1.00000000e-10 1.42296447e-01]
Chi-Square Statistic: 112819999997139.78
p-value: 0.0
Reject the null hypothesis: The data does not follow a negative binomial distribution.


/Users/liuruoque/Desktop/M2R/M2R_Group_12/iz/iz.py:36: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '51.948051948051955' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df1.iloc[i] = df1.iloc[i] / listfinal[i] * s_n
/Users/liuruoque/Desktop/M2R/M2R_Group_12/iz/iz.py:36: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '12.987012987012989' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df1.iloc[i] = df1.iloc[i] / listfinal[i] * s_n
/Users/liuruoque/Desktop/M2R/M2R_Group_12/iz/iz.py:36: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '99.56709956709956' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df1.iloc[i] = df1.iloc[i] / 

(112819999997139.78, 0.0, 19.352504477245475, 0.1057003571656948)

In [4]:
file_path = 'datasets/Donor1_CD4_Genes.csv'
df2 = pd.read_csv(file_path)

file_path_meta = 'datasets/mt_genes_metadata.csv'
dfmeta = pd.read_csv(file_path_meta)

protein_coding_genes = dfmeta[dfmeta['gene_type'] == 'protein_coding']
protein_names = protein_coding_genes['gene_name'].tolist()
tRNA_coding_genes = dfmeta[dfmeta['gene_type']=='Mt_tRNA']
tRNA_names = tRNA_coding_genes['gene_name'].tolist()
rRNA_coding_genes = dfmeta[dfmeta['gene_type']=='Mt_rRNA']
rRNA_names = rRNA_coding_genes['gene_name'].tolist()

umi = df2["non-MT"]

iz.negative_binomial_gof(iz.norm1(df1, umi)["MT-ND1"])

250070.22420512204
Estimated parameters: r = 1.145982649715101, p = 0.0003417475442269378
Observed frequencies:
 [53  1  1 ...  1  1  1]
Expected frequencies:
 [2.887e+03 1.000e-10 1.000e-10 ... 1.000e-10 1.000e-10 1.000e-10]
Chi-Square Statistic: 28399999997113.973
p-value: 0.0
Reject the null hypothesis: The data does not follow a negative binomial distribution.


(28399999997113.973, 0.0, 1.145982649715101, 0.0003417475442269378)

Now try it after removing the outliers:

In [5]:
df14 = iz.remove_otl(iz.dfg(1,4))
df18 = iz.remove_otl(iz.dfg(1,8))
df24 = iz.remove_otl(iz.dfg(2,4))
df18 = iz.remove_otl(iz.dfg(2,8))

In [7]:
iz.negative_binomial_gof(df14["MT-CO3"])

Estimated parameters: r = 6.003426302036768, p = 0.1923663515622145
Observed frequencies:
 [  1   4   7  11  11  12  26  35  32  36  39  54  74  78  68  88  92 107
 101  82  98  84 120  78 110  89  90 102  98  80  76  68  58  61  59  47
  49  44  40  55  39  28  35  23  37  21  19  17  14  11  11  14   8   7
   5   5   3   7   6   4   2   3   2   1   1   1   2   1   1]
Expected frequencies:
 [  0.14106973   0.68398633   1.93438268   4.16784438   7.57658887
  12.24240941  18.13251279  25.11190082  32.96566232  41.42552404
  50.19643393  58.98037897  67.49586395  75.49242536  82.76022414
  89.13518995  94.50042541  98.78467147 101.95862906 104.02986365
 105.03691647 105.04312893 104.13057011 102.39434839  99.93749413
  96.86652147  93.28771443  89.30413536  85.01331914  80.50559414
  75.862957    71.15842227  66.45576714  61.80959442  57.26564297
  52.86128205  48.6261342   44.58277971  40.74750394  37.13105611
  33.73939533  30.57440554  27.63456629  24.91557067  22.41088535
  20.112250

(116.7665309413222,
 0.00021688852355615084,
 6.003426302036768,
 0.1923663515622145)

In [8]:
iz.negative_binomial_gof(iz.norm2(df14)["MT-CO3"])

/Users/liuruoque/Desktop/M2R/M2R_Group_12/iz/iz.py:36: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '51.948051948051955' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df1.iloc[i] = df1.iloc[i] / listfinal[i] * s_n
/Users/liuruoque/Desktop/M2R/M2R_Group_12/iz/iz.py:36: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '12.987012987012989' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df1.iloc[i] = df1.iloc[i] / listfinal[i] * s_n
/Users/liuruoque/Desktop/M2R/M2R_Group_12/iz/iz.py:36: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '99.56709956709956' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df1.iloc[i] = df1.iloc[i] / 

Estimated parameters: r = 19.12945977877652, p = 0.10450014213765911
Observed frequencies:
 [1 1 1 ... 1 1 1]
Expected frequencies:
 [1.00000000e-10 1.00000000e-10 1.00000000e-10 ... 1.00000000e-10
 1.00000000e-10 1.56012352e-01]
Chi-Square Statistic: 109489999997234.81
p-value: 0.0
Reject the null hypothesis: The data does not follow a negative binomial distribution.


(109489999997234.81, 0.0, 19.12945977877652, 0.10450014213765911)